auth_server:
    authorization_endpoint: "http://localhost:4567/authorize"
    token_endpoint: "http://localhost:4567/token"
clients:
    - client_id: "oauth-client-1"
      client_secret: "oauth-client-secret-1"
      redirect_uris:
          - "http://localhost:4568/callback"
      scope: "foo bar"
